# yaml-language-server: $schema=https://coderabbit.ai/integrations/
language: "en-US"

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  sequence_diagrams: true
  auto_review
    enabled: false
  
chat:
  auto_reply: false