[tools]
"aqua:JohnnyMorganz/StyLua" = "2.5.2"
"aqua:Kampfkarren/selene" = "0.31.0"
"github:jackTabsCode/asphalt" = "2.0.2"
"github:luau-lang/lute" = "1.0.0"
"github:pesde-pkg/pesde" = "0.7.3+registry.0.2.3"
"github:rojo-rbx/rojo" = "7.7.0"
"github:seaofvoices/darklua" = "0.19.0"
just = "1.55.1"
mprocs = "0.9.6"